2025-05-01 20:35:08,031 INFO    MainThread:97594 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2025-05-01 20:35:08,031 INFO    MainThread:97594 [wandb_setup.py:_flush():68] Configure stats pid to 97594
2025-05-01 20:35:08,031 INFO    MainThread:97594 [wandb_setup.py:_flush():68] Loading settings from /home/joaopaulo/.config/wandb/settings
2025-05-01 20:35:08,031 INFO    MainThread:97594 [wandb_setup.py:_flush():68] Loading settings from /home/joaopaulo/Projects/internvl3-siamese/notebooks/wandb/settings
2025-05-01 20:35:08,031 INFO    MainThread:97594 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-05-01 20:35:08,031 INFO    MainThread:97594 [wandb_init.py:_log_setup():528] Logging user logs to /home/joaopaulo/Projects/internvl3-siamese/notebooks/wandb/run-20250501_203508-kwq209dq/logs/debug.log
2025-05-01 20:35:08,031 INFO    MainThread:97594 [wandb_init.py:_log_setup():529] Logging internal logs to /home/joaopaulo/Projects/internvl3-siamese/notebooks/wandb/run-20250501_203508-kwq209dq/logs/debug-internal.log
2025-05-01 20:35:08,031 INFO    MainThread:97594 [wandb_init.py:init():639] calling init triggers
2025-05-01 20:35:08,031 INFO    MainThread:97594 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {'model': 'OpenGVLab/InternVL3-8B', 'embedding_strategy': 'last_hidden_mean', 'distance': 'euclidean'}
2025-05-01 20:35:08,031 INFO    MainThread:97594 [wandb_init.py:init():683] wandb.init() called when a run is still active
2025-05-01 20:35:08,031 ERROR   MainThread:97594 [wandb_init.py:init():1315] error in wandb.init()
Traceback (most recent call last):
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1305, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 684, in init
    with telemetry.context() as tel:
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 791, in _telemetry_callback
    self._telemetry_flush()
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 804, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 222, in send_record_publish
    self.send_server_request(server_req)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/joaopaulo/envs/pytorch/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-01 20:35:08,600 INFO    MainThread:97594 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-05-01 20:35:08,600 INFO    MainThread:97594 [wandb_init.py:_pause_backend():439] pausing backend
2025-05-01 20:35:19,685 INFO    MainThread:97594 [wandb_init.py:_resume_backend():444] resuming backend
2025-05-01 20:35:19,775 INFO    MainThread:97594 [wandb_run.py:_finish():2169] finishing run jpcosta1990-university-of-brasilia/siamese-internvl-zsl/azg1o5c7
2025-05-01 20:35:19,942 INFO    MainThread:97594 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2025-05-01 20:35:19,943 INFO    MainThread:97594 [wandb_init.py:_pause_backend():439] pausing backend
